all:
  vars:
    ansible_user: ansible
    
  children:
    app:
      hosts:
        vm2:
          ansible_host: 89.169.145.67
        vm3:
          ansible_host: 158.160.58.175
    database:
      hosts:
        vm1:
          ansible_host: 89.169.137.117
          pg_version: 14
          pg_data_dir: /var/lib/pgsql/14/data
    web:                           
      hosts:
        vm1:
