---
- name: Add PostgreSQL APT key
  apt_key:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    state: present
  when: ansible_os_family == "Debian"

- name: Add PostgreSQL repository
  apt_repository:
    repo: "deb http://apt.postgresql.org/pub/repos/apt {{ ansible_distribution_release }}-pgdg main"
    filename: "postgresql"
    state: present
  when: ansible_os_family == "Debian"

- name: Install PostgreSQL server
  apt:
    name: "postgresql-{{ pg_version }}"
    state: present
    update_cache: yes
  when: ansible_os_family == "Debian"

- name: Ensure data directory exists (на всякий случай)
  file:
    path: "{{ pg_data_dir }}"
    state: directory
    owner: postgres
    group: postgres
    mode: '0700'

- name: Enable & start PostgreSQL
  service:
    name: postgresql
    state: started
    enabled: yes
  notify: restart postgresql
